function newrules = saNeuralBlocks(obj)
  newrules = {};
  
  ver = obj.ver;
  if ver.isR2009aOrEarlier

    % Conversion for blocks created in NNT 7.0 R2010b - Present

    % The MaskDisplay parameters of generated neural network blocks in
    % R2010b and forward use variable and calculations which are not
    % supported in R2009a or earlier.
    
    % This conversion finds such blocks, which all have MaskDisplay
    % parameters starting with 'e = 0.06;' then removes the MaskDisplay
    % and enables the MaskIconFrame so these blocks return to their
    % default look.
    
    % Blocks generated by GENSIM with such MaskDisplay properties can
    % be of the following types:
    
    %   Constant, Display, From, FromWorkspace, Goto, Inport, Mux,
    %   Output, Product, Scope, SubSystem, Sum and ToWorkspace.
    
    % Blocks with MaskType of [] are not altered as they are references
    % to the neural block library and those blocks will revert to their
    % old appearance automatically.

    blocks = find_system(obj.modelName,'LookUnderMasks','all','Regexp','on','MaskDisplay','^e = 0\.06;','MaskType',[]);
    for i=1:numel(blocks)
      blk = blocks{i};
      set_param(blk,'MaskDisplay','');
      set_param(blk,'MaskIconFrame','on');
    end

  end
end
